### ISSUE TITLE
React.PropTypes is imported but never used

### ISSUE THREAD

**Issue by th0th** [samsch/basic-redux#1]
Hi,

I noticed there is a line in `src/containers/App.js`:

```
let PropTypes = React.PropTypes;
```

but it is never used. What is it needed for?

**Comment by samsch** [comment]
That'd be a left-over from a component generation snippet in my editor.

I'm going to remove it from the example for the sake of simplicity, but good practice would be leaving it in, and using [property validation](https://facebook.github.io/react/docs/reusable-components.html) on your components.

Thanks for the catch!
